import { createClient } from '@supabase/supabase-js'

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY

export const supabase = createClient(supabaseUrl, supabaseAnonKey)

// Session-less client for CHILD-side Storage uploads. The child is anonymous
// (family-code, not Supabase auth), but the shared `supabase` singleton above
// persists a parent session when a parent has logged in on the same device.
// That parent JWT turns the request into role=authenticated, and the
// 'submissions' bucket's INSERT policy is granted to the anon role only — so
// the upload fails with "new row violates row-level security policy". This
// client never carries a session, so child uploads always go as anon.
export const storageClient = createClient(supabaseUrl, supabaseAnonKey, {
  // persistSession:false → never loads the parent's persisted session; a
  // distinct storageKey keeps it off the shared auth-token key entirely (no
  // "Multiple GoTrueClient instances… same storage key" collision).
  auth: { persistSession: false, autoRefreshToken: false, storageKey: 'tuto-anon-upload' },
})

const SERVER = import.meta.env.VITE_SERVER_URL || 'https://tuto-production-d1db.up.railway.app'

// Private bucket for real photos of a child's homework / room. Readable only
// via short-lived signed URLs minted server-side. Story covers stay in the
// public 'submissions' bucket (AI cover art, rendered by the child app which
// has no Supabase session).
export const PHOTO_BUCKET = 'submission-photos'

// There is deliberately no painting-bucket constant here: the client never
// touches that bucket. Drawing photos go through the server, which screens them
// and writes with the service role (see submitPainting below).

// Generic guided-step sketches. Public on purpose: no child data, and a public
// bucket means CDN caching and stable URLs with no signing per panel.
export const DRAWINGS_BUCKET = 'drawings'

// Panel URLs are DERIVED, never stored in the database — id + age group + step
// number is all it takes.
export function drawingStepUrl(drawingId, ageGroup, step) {
  const n = String(step).padStart(2, '0')
  return `${supabaseUrl}/storage/v1/object/public/${DRAWINGS_BUCKET}/${drawingId}/${ageGroup}/step-${n}.webp`
}

// A small (~160px) derivative of a drawing's finished panel, for places that
// show it as an ICON rather than a guide to follow — e.g. the ChildHome tile,
// which mounts on every app open. The full step-08 panel is ~1024px and
// several hundred KB; this is the same picture at icon size, a few KB.
// Generated by server/scripts/make_drawing_icons.mjs.
export function drawingIconUrl(drawingId, ageGroup) {
  return `${supabaseUrl}/storage/v1/object/public/${DRAWINGS_BUCKET}/${drawingId}/${ageGroup}/icon.webp`
}

// The guided-drawing catalogue for an age band.
export async function getDrawings(ageGroup) {
  try {
    const res = await fetch(`${SERVER}/api/drawings?age_group=${encodeURIComponent(ageGroup)}`)
    const data = await res.json()
    return data.drawings || []
  } catch (err) {
    console.error('[getDrawings] error:', err.message)
    return []
  }
}

// Shrinks a camera photo before it goes over the wire. A raw phone capture is
// several MB; a drawing on paper needs none of that resolution.
async function downscale(file, maxEdge = 1600, quality = 0.85) {
  const bitmap = await createImageBitmap(file)
  const scale = Math.min(1, maxEdge / Math.max(bitmap.width, bitmap.height))
  const w = Math.round(bitmap.width * scale)
  const h = Math.round(bitmap.height * scale)
  const canvas = document.createElement('canvas')
  canvas.width = w
  canvas.height = h
  canvas.getContext('2d').drawImage(bitmap, 0, 0, w, h)
  bitmap.close?.()
  const blob = await new Promise(r => canvas.toBlob(r, 'image/jpeg', quality))
  return blob || file
}

function blobToBase64(blob) {
  return new Promise((resolve, reject) => {
    const reader = new FileReader()
    reader.onload = () => resolve(String(reader.result).split(',')[1])
    reader.onerror = reject
    reader.readAsDataURL(blob)
  })
}

// Sends the finished-drawing photo THROUGH the backend.
//
// The bytes deliberately do not go straight to Storage the way homework and
// chore photos do. That route needs an anon insert policy on the bucket, and
// child ids are discoverable — so anyone with a family code could drop files
// into a child's folder. Here the server is the only writer, and it screens the
// image before storing it. It is one photo, so the round trip is cheap.
//
// Note what is NOT sent: any gem or XP amount. The reward is the server's
// decision (it also applies the daily cap) — the client only reports the event
// and renders whatever the server says it awarded.
export async function submitPainting(childId, file, { drawingId = null, ageGroup = null } = {}) {
  let payload
  try {
    payload = await downscale(file)
  } catch {
    payload = file   // canvas unavailable — send the original
  }

  const res = await fetch(`${SERVER}/api/children/${encodeURIComponent(childId)}/paintings`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      photo_base64: await blobToBase64(payload),
      mime_type: payload.type || 'image/jpeg',
      drawing_id: drawingId,
      age_group: ageGroup,
    }),
  })
  const data = await res.json()
  if (!res.ok) throw new Error(data?.message || data?.error || `Server error ${res.status}`)
  return data   // { painting, awarded, capped, dailyCap }
}

// The child's saved paintings, newest first, with freshly signed photo URLs.
export async function getPaintings(childId) {
  try {
    const res = await fetch(`${SERVER}/api/children/${encodeURIComponent(childId)}/paintings`)
    const data = await res.json()
    return data.paintings || []
  } catch (err) {
    console.error('[getPaintings] error:', err.message)
    return []
  }
}

export async function getChildrenByFamilyCode(familyCode) {
  try {
    const res = await fetch(`${SERVER}/api/family/${encodeURIComponent(familyCode)}/children`)
    const data = await res.json()
    return data.children || []
  } catch (err) {
    console.error('[getChildren] error:', err.message)
    return []
  }
}

export async function getChildRewards(childId) {
  try {
    const res = await fetch(`${SERVER}/api/children/${encodeURIComponent(childId)}/rewards`)
    const data = await res.json()
    return data.rewards || []
  } catch (err) {
    console.error('[getChildRewards] error:', err.message)
    return []
  }
}

export async function getChildGems(childId) {
  try {
    const res = await fetch(`${SERVER}/api/children/${encodeURIComponent(childId)}/gems`)
    const data = await res.json()
    return data.gems ?? 0
  } catch (err) {
    console.error('[getChildGems] error:', err.message)
    return 0
  }
}

export async function getStoryIdeas(childId) {
  try {
    const res = await fetch(`${SERVER}/api/children/${encodeURIComponent(childId)}/story-ideas`)
    const data = await res.json()
    return data.ideas || []
  } catch {
    return []
  }
}

export async function getChildStories(childId) {
  try {
    const res = await fetch(`${SERVER}/api/children/${encodeURIComponent(childId)}/stories`)
    const data = await res.json()
    return data.stories || []
  } catch (err) {
    console.error('[getChildStories] error:', err.message)
    return []
  }
}

export async function saveChildStory(childId, storyData) {
  const res = await fetch(`${SERVER}/api/children/${encodeURIComponent(childId)}/stories`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(storyData),
  })
  const data = await res.json()
  if (!res.ok) throw new Error(data?.error || `Server error ${res.status}`)
  return data
}

export async function deleteChildStory(childId, storyId) {
  const res = await fetch(`${SERVER}/api/children/${encodeURIComponent(childId)}/stories/${encodeURIComponent(storyId)}`, {
    method: 'DELETE',
  })
  const data = await res.json()
  if (!res.ok) throw new Error(data?.error || `Server error ${res.status}`)
  return data
}

function fileToBase64(file) {
  return new Promise((resolve, reject) => {
    const reader = new FileReader()
    reader.onload = () => resolve(reader.result.split(',')[1])
    reader.onerror = reject
    reader.readAsDataURL(file)
  })
}

export async function uploadStoryCover(childId, file) {
  const imageBase64 = await fileToBase64(file)
  const res = await fetch(`${SERVER}/api/children/${encodeURIComponent(childId)}/stories/cover`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ imageBase64, mimeType: file.type || 'image/jpeg' }),
  })
  const data = await res.json()
  if (!res.ok) throw new Error(data?.error || `Server error ${res.status}`)
  return data.cover_url
}

// Uploads homework photos (1..15) DIRECTLY to Storage from the client (same
// pattern as chore's uploadPhoto), then sends only the storage PATHS to the
// backend. This keeps the JSON body tiny (15 photos as base64 would blow past
// the server's body limit) AND leaves the original bytes — with EXIF intact —
// on the server side to read. The server still does EXIF/Gemini/screening/gems
// and writes the PENDING submission; no gem math here by design.
export async function submitHomework(childId, files) {
  const cid = childId || 'anonymous'
  const paths = []
  for (let i = 0; i < files.length; i++) {
    const file = files[i]
    const ext = (file.type || '').includes('png') ? 'png' : 'jpg'
    const path = `${cid}/homework/${Date.now()}-${i}.${ext}`
    const { error } = await storageClient.storage
      .from(PHOTO_BUCKET)
      .upload(path, file, { contentType: file.type || 'image/jpeg', upsert: false })
    if (error) throw error
    paths.push(path)
  }

  const res = await fetch(`${SERVER}/api/children/${encodeURIComponent(childId)}/homework`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ paths }),
  })
  const data = await res.json()
  if (!res.ok) throw new Error(data?.error || `Server error ${res.status}`)
  return data
}

// Answers the "did you do this homework today?" question the server asks when
// the photo had no readable date. Releases the held parent notification.
export async function confirmHomeworkDate(submissionId, doneToday) {
  try {
    await fetch(`${SERVER}/api/homework/${encodeURIComponent(submissionId)}/confirm-date`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ doneToday }),
    })
  } catch (err) {
    console.error('[confirmHomeworkDate] error:', err.message)
  }
}

// Recent homework submissions (last 7 days), newest first, for the child-side
// "This week" history list. Rows: { id, date (ISO), pages, status }.
export async function getHomeworkSubmissions(childId) {
  try {
    const res = await fetch(`${SERVER}/api/children/${encodeURIComponent(childId)}/homework`)
    const data = await res.json()
    return data.submissions || []
  } catch (err) {
    console.error('[getHomeworkSubmissions] error:', err.message)
    return []
  }
}

export async function saveSpellingErrors(childId, errors) {
  try {
    await fetch(`${SERVER}/api/children/${encodeURIComponent(childId)}/spelling-errors`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ errors }),
    })
  } catch {}
}
